### ISSUE TITLE
Provide an example please

### ISSUE THREAD

**Issue by m-abyzov** [sepehr3pehr/GeTLO#2]
I'm nooby and do not understand how to launch your code. I have a coverage matrix inside the attached file. How can I launch your code with it?
I have already tried to do it with the "readmatrix" function and providing a way to the file, but it produces me the following error: 
"'coverage' requires one of the following:
  Antenna Toolbox
  Communications Toolbox:"

I do not understand what these toolboxes mean. Please, help me with this issue. Please, provide an example of the correct launching of your project, it is very important for me, especially of launching your code with a coverage matrix which is written in a separate file.

I have read your article and consider that your project is very promising for further investigation and extensions in the part of my thesis work. 

Sincerely, 
Mikhail Abyzov,
Student at Innopolis University.

[Sudoku_1_line_true_Coverage.txt](https://github.com/sepehr3pehr/GeTLO/files/4091994/Sudoku_1_line_true_Coverage.txt)

**Comment by sepehr3pehr** [comment]
Clone the repo, read the file and convert it to a MATLAB matrix (I assume that the last column of your file the cumulative coverage which is not needed and should be removed)
